# Generated by Django 4.0.3 on 2023-06-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='automobilevo',
            old_name='import_href',
            new_name='import_id',
        ),
    ]
