# Generated by Django 4.0.3 on 2023-06-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_rename_import_href_automobilevo_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='sold',
            field=models.BooleanField(),
        ),
    ]
