# Generated by Django 4.0.3 on 2023-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_automobilevo_import_id_alter_automobilevo_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_id',
            field=models.PositiveSmallIntegerField(max_length=200),
        ),
    ]
