# Generated by Django 4.0.3 on 2023-06-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_automobilevo_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='import_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
